name: Daily Login Script

on:
  schedule:
    - cron: "0 14 * * *"  # Runs every day at 2:00 PM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Download ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip xvfb libxi6
          sudo rm -f /usr/local/bin/chromedriver
          wget -q https://chromedriver.storage.googleapis.com/133.0.6943.141/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run the Login Script
        env:
          MYUSERNAME: ${{ secrets.MYUSERNAME }}
          MYPASSWORD: ${{ secrets.MYPASSWORD }}
        run: python jedi_daily_login.py
